/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SalesPaymentsRouteImport } from './routes/sales.payments'
import { Route as ProgramsProgramSlugRouteImport } from './routes/programs.$programSlug'
import { Route as ProductsNewRouteImport } from './routes/products.new'
import { Route as ProductsProductIdRouteImport } from './routes/products.$productId'
import { Route as CoursesCourseIdRouteImport } from './routes/courses.$courseId'
import { Route as CheckoutCourseIdRouteImport } from './routes/checkout.$courseId'
import { Route as BootcampsNewRouteImport } from './routes/bootcamps.new'
import { Route as CoursesLearnCourseIdRouteImport } from './routes/courses.learn.$courseId'

const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesPaymentsRoute = SalesPaymentsRouteImport.update({
  id: '/sales/payments',
  path: '/sales/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsProgramSlugRoute = ProgramsProgramSlugRouteImport.update({
  id: '/programs/$programSlug',
  path: '/programs/$programSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsNewRoute = ProductsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => ProductsRoute,
} as any)
const CoursesCourseIdRoute = CoursesCourseIdRouteImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => CoursesRoute,
} as any)
const CheckoutCourseIdRoute = CheckoutCourseIdRouteImport.update({
  id: '/checkout/$courseId',
  path: '/checkout/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const BootcampsNewRoute = BootcampsNewRouteImport.update({
  id: '/bootcamps/new',
  path: '/bootcamps/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesLearnCourseIdRoute = CoursesLearnCourseIdRouteImport.update({
  id: '/learn/$courseId',
  path: '/learn/$courseId',
  getParentRoute: () => CoursesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/courses': typeof CoursesRouteWithChildren
  '/products': typeof ProductsRouteWithChildren
  '/bootcamps/new': typeof BootcampsNewRoute
  '/checkout/$courseId': typeof CheckoutCourseIdRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/products/new': typeof ProductsNewRoute
  '/programs/$programSlug': typeof ProgramsProgramSlugRoute
  '/sales/payments': typeof SalesPaymentsRoute
  '/courses/learn/$courseId': typeof CoursesLearnCourseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/courses': typeof CoursesRouteWithChildren
  '/products': typeof ProductsRouteWithChildren
  '/bootcamps/new': typeof BootcampsNewRoute
  '/checkout/$courseId': typeof CheckoutCourseIdRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/products/new': typeof ProductsNewRoute
  '/programs/$programSlug': typeof ProgramsProgramSlugRoute
  '/sales/payments': typeof SalesPaymentsRoute
  '/courses/learn/$courseId': typeof CoursesLearnCourseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/courses': typeof CoursesRouteWithChildren
  '/products': typeof ProductsRouteWithChildren
  '/bootcamps/new': typeof BootcampsNewRoute
  '/checkout/$courseId': typeof CheckoutCourseIdRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/products/new': typeof ProductsNewRoute
  '/programs/$programSlug': typeof ProgramsProgramSlugRoute
  '/sales/payments': typeof SalesPaymentsRoute
  '/courses/learn/$courseId': typeof CoursesLearnCourseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/courses'
    | '/products'
    | '/bootcamps/new'
    | '/checkout/$courseId'
    | '/courses/$courseId'
    | '/products/$productId'
    | '/products/new'
    | '/programs/$programSlug'
    | '/sales/payments'
    | '/courses/learn/$courseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/courses'
    | '/products'
    | '/bootcamps/new'
    | '/checkout/$courseId'
    | '/courses/$courseId'
    | '/products/$productId'
    | '/products/new'
    | '/programs/$programSlug'
    | '/sales/payments'
    | '/courses/learn/$courseId'
  id:
    | '__root__'
    | '/'
    | '/courses'
    | '/products'
    | '/bootcamps/new'
    | '/checkout/$courseId'
    | '/courses/$courseId'
    | '/products/$productId'
    | '/products/new'
    | '/programs/$programSlug'
    | '/sales/payments'
    | '/courses/learn/$courseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoursesRoute: typeof CoursesRouteWithChildren
  ProductsRoute: typeof ProductsRouteWithChildren
  BootcampsNewRoute: typeof BootcampsNewRoute
  CheckoutCourseIdRoute: typeof CheckoutCourseIdRoute
  ProgramsProgramSlugRoute: typeof ProgramsProgramSlugRoute
  SalesPaymentsRoute: typeof SalesPaymentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/payments': {
      id: '/sales/payments'
      path: '/sales/payments'
      fullPath: '/sales/payments'
      preLoaderRoute: typeof SalesPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/$programSlug': {
      id: '/programs/$programSlug'
      path: '/programs/$programSlug'
      fullPath: '/programs/$programSlug'
      preLoaderRoute: typeof ProgramsProgramSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/new': {
      id: '/products/new'
      path: '/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof ProductsNewRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/courses/$courseId': {
      id: '/courses/$courseId'
      path: '/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof CoursesCourseIdRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/checkout/$courseId': {
      id: '/checkout/$courseId'
      path: '/checkout/$courseId'
      fullPath: '/checkout/$courseId'
      preLoaderRoute: typeof CheckoutCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bootcamps/new': {
      id: '/bootcamps/new'
      path: '/bootcamps/new'
      fullPath: '/bootcamps/new'
      preLoaderRoute: typeof BootcampsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/learn/$courseId': {
      id: '/courses/learn/$courseId'
      path: '/learn/$courseId'
      fullPath: '/courses/learn/$courseId'
      preLoaderRoute: typeof CoursesLearnCourseIdRouteImport
      parentRoute: typeof CoursesRoute
    }
  }
}

interface CoursesRouteChildren {
  CoursesCourseIdRoute: typeof CoursesCourseIdRoute
  CoursesLearnCourseIdRoute: typeof CoursesLearnCourseIdRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesCourseIdRoute: CoursesCourseIdRoute,
  CoursesLearnCourseIdRoute: CoursesLearnCourseIdRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

interface ProductsRouteChildren {
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  ProductsNewRoute: typeof ProductsNewRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsProductIdRoute: ProductsProductIdRoute,
  ProductsNewRoute: ProductsNewRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoursesRoute: CoursesRouteWithChildren,
  ProductsRoute: ProductsRouteWithChildren,
  BootcampsNewRoute: BootcampsNewRoute,
  CheckoutCourseIdRoute: CheckoutCourseIdRoute,
  ProgramsProgramSlugRoute: ProgramsProgramSlugRoute,
  SalesPaymentsRoute: SalesPaymentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
